// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: resturant_recommand_proxy.proto

package helloworld

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserLikeDishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *GetUserLikeDishReq) Reset() {
	*x = GetUserLikeDishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_recommand_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLikeDishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLikeDishReq) ProtoMessage() {}

func (x *GetUserLikeDishReq) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_recommand_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLikeDishReq.ProtoReflect.Descriptor instead.
func (*GetUserLikeDishReq) Descriptor() ([]byte, []int) {
	return file_resturant_recommand_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserLikeDishReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserLikeDishReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetUserLikeDishRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    int32   `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Dishes []*Dish `protobuf:"bytes,2,rep,name=dishes,proto3" json:"dishes,omitempty"`
}

func (x *GetUserLikeDishRsp) Reset() {
	*x = GetUserLikeDishRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_recommand_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLikeDishRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLikeDishRsp) ProtoMessage() {}

func (x *GetUserLikeDishRsp) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_recommand_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLikeDishRsp.ProtoReflect.Descriptor instead.
func (*GetUserLikeDishRsp) Descriptor() ([]byte, []int) {
	return file_resturant_recommand_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserLikeDishRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetUserLikeDishRsp) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

type Dish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Dish) Reset() {
	*x = Dish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_recommand_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_recommand_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_resturant_recommand_proxy_proto_rawDescGZIP(), []int{2}
}

var File_resturant_recommand_proxy_proto protoreflect.FileDescriptor

var file_resturant_recommand_proxy_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x72, 0x65, 0x73, 0x74, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x4c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x69, 0x6b, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x48, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x6b, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x06, 0x64,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x69, 0x73, 0x68, 0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x22, 0x06, 0x0a,
	0x04, 0x44, 0x69, 0x73, 0x68, 0x32, 0x50, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x43, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6b,
	0x65, 0x44, 0x69, 0x73, 0x68, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x69, 0x6b, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6b, 0x65, 0x44, 0x69,
	0x73, 0x68, 0x52, 0x65, 0x71, 0x22, 0x00, 0x42, 0x67, 0x0a, 0x1b, 0x69, 0x6f, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resturant_recommand_proxy_proto_rawDescOnce sync.Once
	file_resturant_recommand_proxy_proto_rawDescData = file_resturant_recommand_proxy_proto_rawDesc
)

func file_resturant_recommand_proxy_proto_rawDescGZIP() []byte {
	file_resturant_recommand_proxy_proto_rawDescOnce.Do(func() {
		file_resturant_recommand_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_resturant_recommand_proxy_proto_rawDescData)
	})
	return file_resturant_recommand_proxy_proto_rawDescData
}

var file_resturant_recommand_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_resturant_recommand_proxy_proto_goTypes = []interface{}{
	(*GetUserLikeDishReq)(nil), // 0: pb.GetUserLikeDishReq
	(*GetUserLikeDishRsp)(nil), // 1: pb.GetUserLikeDishRsp
	(*Dish)(nil),               // 2: pb.Dish
}
var file_resturant_recommand_proxy_proto_depIdxs = []int32{
	2, // 0: pb.GetUserLikeDishRsp.dishes:type_name -> pb.Dish
	0, // 1: pb.Recommand.GetUserLikeDish:input_type -> pb.GetUserLikeDishReq
	0, // 2: pb.Recommand.GetUserLikeDish:output_type -> pb.GetUserLikeDishReq
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resturant_recommand_proxy_proto_init() }
func file_resturant_recommand_proxy_proto_init() {
	if File_resturant_recommand_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resturant_recommand_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserLikeDishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_recommand_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserLikeDishRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_recommand_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resturant_recommand_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resturant_recommand_proxy_proto_goTypes,
		DependencyIndexes: file_resturant_recommand_proxy_proto_depIdxs,
		MessageInfos:      file_resturant_recommand_proxy_proto_msgTypes,
	}.Build()
	File_resturant_recommand_proxy_proto = out.File
	file_resturant_recommand_proxy_proto_rawDesc = nil
	file_resturant_recommand_proxy_proto_goTypes = nil
	file_resturant_recommand_proxy_proto_depIdxs = nil
}
